[package]
name = "assignment7_q2"
version = "0.1.0"
authors = ["Raashid Mehmood <raashidmehmood1978@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
